# Generated by Django 4.1.3 on 2023-03-07 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_name_user_username_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parts_db',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('part_name', models.CharField(default=False, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Project_db',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(default=False, max_length=200)),
                ('project_pricing', models.CharField(default=False, max_length=200)),
                ('inventory', models.CharField(default=False, max_length=200)),
                ('working_status', models.CharField(default=False, max_length=200)),
                ('project_description', models.CharField(default=False, max_length=200)),
                ('emp', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task_db',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('parts_quantity', models.IntegerField(default=False, max_length=200)),
                ('opretions', models.CharField(default=False, max_length=200)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parts_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.parts_db')),
                ('projet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.project_db')),
            ],
        ),
        migrations.CreateModel(
            name='Timesheet_db',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('time_spent', models.CharField(default=False, max_length=200)),
                ('check_in', models.DateTimeField(auto_now_add=True)),
                ('check_out', models.DateTimeField(auto_now_add=True)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parts_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.parts_db')),
                ('projet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.project_db')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.task_db')),
            ],
        ),
        migrations.AddField(
            model_name='parts_db',
            name='projet_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.project_db'),
        ),
    ]
