# Generated by Django 4.1.3 on 2023-03-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_parts_db_project_db_task_db_timesheet_db_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_db',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='timesheet_db',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
