# Generated by Django 4.1.3 on 2023-03-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_project_db_id_alter_timesheet_db_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet_db',
            name='check_out',
            field=models.DateTimeField(blank=True),
        ),
    ]
