# Generated by Django 4.1.7 on 2023-03-10 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_parts_db_id_alter_task_db_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet_db',
            name='parts_id',
        ),
        migrations.RemoveField(
            model_name='timesheet_db',
            name='projet_id',
        ),
        migrations.RemoveField(
            model_name='timesheet_db',
            name='task_id',
        ),
        migrations.AddField(
            model_name='timesheet_db',
            name='parts_id',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='parts_db', to='account.parts_db'),
        ),
        migrations.AddField(
            model_name='timesheet_db',
            name='projet_id',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='project_id', to='account.project_db'),
        ),
        migrations.AddField(
            model_name='timesheet_db',
            name='task_id',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='task_db', to='account.task_db'),
        ),
    ]
