# Generated by Django 4.1.7 on 2023-03-10 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_remove_timesheet_db_parts_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parts_db',
            name='emp_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
